import { NavLink, Outlet, Navigate } from 'react-router-dom';
import { Activity, CalendarDays, ChevronRight, ClipboardList, LayoutDashboard, LogOut, Menu, Settings, ShieldCheck, Users, UserRound, X } from 'lucide-react';
import { useState } from 'react'; import { useAuth } from '../context/AuthContext'; import { Loading } from './UI';
const nav=[['Dashboard','/',LayoutDashboard],['Patients','/patients',UserRound],['Medical records','/records',ClipboardList],['Appointments','/appointments',CalendarDays],['Users','/users',Users],['Settings','/settings',Settings]] as const;
export function ProtectedLayout(){const {user,loading,logout}=useAuth();const [open,setOpen]=useState(false);if(loading)return <Loading/>;if(!user)return <Navigate to="/login" replace/>;return <div className="min-h-screen bg-slate-50">
 <button className="fixed left-4 top-4 z-30 rounded-xl bg-white p-2 shadow md:hidden" onClick={()=>setOpen(true)}><Menu/></button>
 {open&&<div className="fixed inset-0 z-30 bg-slate-950/30 md:hidden" onClick={()=>setOpen(false)}/>}<aside className={`fixed inset-y-0 left-0 z-40 flex w-64 flex-col bg-[#102f3b] text-white transition-transform md:translate-x-0 ${open?'translate-x-0':'-translate-x-full'}`}>
 <div className="flex h-20 items-center gap-3 border-b border-white/10 px-6"><div className="rounded-xl bg-brand-500 p-2"><Activity size={22}/></div><div><div className="font-bold">ClinicFlow</div><div className="text-xs text-slate-400">Electronic Medical Records</div></div><button className="ml-auto md:hidden" onClick={()=>setOpen(false)}><X/></button></div>
 <nav className="flex-1 space-y-1 p-4">{nav.filter(([label])=>label!=='Users'||user.role==='ADMIN').map(([label,to,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)} className={({isActive})=>`flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium transition ${isActive?'bg-brand-500 text-white':'text-slate-300 hover:bg-white/5 hover:text-white'}`}><Icon size={18}/>{label}<ChevronRight size={14} className="ml-auto opacity-40"/></NavLink>)}</nav>
 <div className="border-t border-white/10 p-4"><div className="mb-3 flex items-center gap-3 px-2"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-brand-600 text-sm font-bold">{user.firstName[0]}{user.lastName[0]}</div><div className="min-w-0"><div className="truncate text-sm font-semibold">{user.firstName} {user.lastName}</div><div className="text-xs text-slate-400">{user.role}</div></div></div><button className="flex w-full items-center gap-3 rounded-xl px-3 py-2 text-sm text-slate-300 hover:bg-white/5" onClick={logout}><LogOut size={17}/> Sign out</button></div></aside>
 <main className="min-h-screen md:pl-64"><header className="flex h-20 items-center justify-end border-b border-slate-200/80 bg-white px-6 lg:px-10"><div className="flex items-center gap-2 rounded-full bg-brand-50 px-3 py-1.5 text-xs font-semibold text-brand-700"><ShieldCheck size={15}/> Fake demo data only</div></header><div className="mx-auto max-w-7xl p-5 pt-8 lg:p-10"><Outlet/></div></main></div>}

